name: Preview Deployment

on:
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install serve
        run: npm install -g serve
        
      - name: Start preview server
        run: |
          echo "Starting preview server..."
          serve -s . -l 3000 &
          sleep 5
          
      - name: Comment PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview Deployment Ready!**
              
              Your changes are ready for review. You can test the site locally by running:
              \`\`\`bash
              npx serve -s . -l 3000
              \`\`\`
              
              Then visit: http://localhost:3000
              
              **Note:** For a live preview URL, you can use services like:
              - [Netlify Drop](https://app.netlify.com/drop) - Drag and drop your files
              - [Vercel](https://vercel.com) - Connect your GitHub repo
              - [GitHub Pages](https://pages.github.com) - Enable Pages in repo settings`
            })